all:
  hosts:
    node1:
      ansible_host: 10.10.21.43
      ip: 10.10.21.43
      access_ip: 10.10.21.43
    node2:
      ansible_host: 10.10.21.40
      ip: 10.10.21.40
      access_ip: 10.10.21.40
    node3:
      ansible_host: 10.10.21.41
      ip: 10.10.21.41
      access_ip: 10.10.21.41
    node4:
      ansible_host: 10.10.21.45
      ip: 10.10.21.45
      access_ip: 10.10.21.45
    node5:
      ansible_host: 10.10.21.51
      ip: 10.10.21.51
      access_ip: 10.10.21.51
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
