apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-nginx-static
  namespace: default
spec:
  containers:
  - name: csi-s3-test-nginx-static
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html/s3
        name: s3-volume
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: csi-s3-pvc
        readOnly: false
