apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: default
type: Opaque
data:
  access-key-id: YWplaGZuMDU5dHVrc2t1NTdjYW8=
  secret-access-key: WUNQR002c2RfVHdva1VoeTFtbVh0akJldXI0eVNuOVBid2pqc3cweA==

# yc iam access-key create --service-account-name sa-for-kubernetes-csi-bucket --description "this key is for my bucket"
# echo -n '<access-key-id>' | base64
# echo -n '<secret-access-key>' | base64