apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: YCAJELPw4naGNFFHg4Hq_R5mu
  secretAccessKey: YCM5lXUkwqNNnVcBNCzxQrpbQto2tWs66QWJ72jF
  endpoint: https://storage.yandexcloud.net/



# yc iam access-key create --service-account-name sa-for-kubernetes-csi-bucket --description "this key is for my bucket"
# echo -n '<access-key-id>' | base64
# echo -n '<secret-access-key>' | base64