apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
  finalizers: []
spec:
  group: otus.homework
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
                description: 'Docker-image'
              database:
                type: string
                description: 'DB name'
              password:
                type: string
                description: 'DB pass'
              storage_size:
                type: string
                default: "1"
                description: 'DB pass'
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
    