apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full-access-cluster-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["mysqls", "deployments"]
    verbs: ["*"]
  - apiGroups: ["*"]
    resources: ["services", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: user
    namespace: default
roleRef:
  kind: ClusterRole
  name: full-access-cluster-role
  apiGroup: rbac.authorization.k8s.io