apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimal-access-cluster-role
rules:
  - apiGroups: ["otus.homework"]
    resources: ["mysqls"]
    verbs: ["create", "delete", "get", "list", "update", "watch", "patch"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumes", "persistentvolumeclaims", "deployments/status", "events"]
    verbs: ["create", "delete", "watch", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minimal-access-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: user
    namespace: default
roleRef:
  kind: ClusterRole
  name: minimal-access-cluster-role
  apiGroup: rbac.authorization.k8s.io
