apiVersion: otus.homework/v1
kind: MySQL
metadata:
  name: mysql-custom-object-new2
  finalizers: []
spec:
  image: mysql:5.7.43
  database: mydb
  password: mysecretpassword
  storage_size: 1Gi
  


# Delete: kubectl patch crd/mysqls.otus.homework -p '{"metadata":{"finalizers":[]}}' --type=merge