apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: prometheus
data:
  nginx.conf: |
    server {
        listen 8000;
        root /homework;
        location = /basic_status {
          stub_status;
        }
    }