apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: homework
  labels:
    name: web-server
spec:
  initContainers:
  - name: init-busybox
    image: busybox:latest
    command: ['sh', '-c', 'cd /init && wget -O /init/index.html --no-check-certificate https://www.onliner.by/index.html']
    volumeMounts:
    - mountPath: /init
      name: shared-volume
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: shared-volume
      mountPath: /homework
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "rm -f /homework/index.html"]
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
  - name: shared-volume
    emptyDir:
      sizeLimit: 50Mi




# Used commands:

# minikube start --force
# kubectl get namespaces
# kubectl config set-context --current --namespace=homework
# kubectl get po -A
# kubectl get svc
# kubectl apply -f pod.yaml
# kubectl describe pod web-server -n homework
# kubectl logs web-server -c init-busybox -n homework
# kubectl delete pod web-server -n homework