deploymentMode: SingleBinary
loki:
  auth_enabled:  false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h    
  storage:
    type: 's3'
    bucketNames:
      chunks: 'bokhanych-loki-logs'
      ruler: 'bokhanych-loki-logs'
      admin: 'bokhanych-loki-logs'
    s3: 
      endpoint: https://storage.yandexcloud.net
      region: ru-central1
      secretAccessKey: YCOOSovtzGFxdiPgiL_iPvZ4T6dJjOwqHILrRALd
      accessKeyId: YCAJEwFCbLPsgEUmuVFWpL56z
      s3ForcePathStyle: false
      insecure: false
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0    
singleBinary:
  replicas: 1
  tolerations:
    - key: 'node-role'
      effect: 'NoSchedule'
      operator: 'Equal'
      value: 'infra'
  nodeSelector:
    node-role: 'infra'  

chunksCache:
  tolerations:
    - key: 'node-role'
      effect: 'NoSchedule'
      operator: 'Equal'
      value: 'infra'
  nodeSelector:
    node-role: 'infra'  
  allocatedMemory: 2048 
