apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name      : app-templating
  namespace : argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: otus
  source:
    repoURL       : 'git@github.com:Kuber-2024-04OTUS/bokhanych_repo.git'
    targetRevision: HEAD
    path          : 'kubernetes-templating/work_1'
    directory:
      exclude: '3_storages.yaml'
    helm:
      valueFiles:
        - values.yaml
      parameters:
      - name: general.namespace
        value: homeworkhelm
      - name: resources.replicaCount
        value: '1'
  destination:
    name     : in-cluster
    namespace: homeworkhelm
  sources: []
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      