apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-vault-ui
  namespace: vault
spec:
  ingressClassName: nginx
  rules:
  - host: vault.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault-ui
            port:
              name: http