apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-consul-ui
  namespace: consul
spec:
  ingressClassName: nginx
  rules:
  - host: consul.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: consul-ui
            port:
              name: http