apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bokhanych-storageclass
  namespace: homework
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bokhanych-pvc
  namespace: homework
spec: 
  storageClassName: "bokhanych-storageclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi