apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault
type: Opaque
data:
  token: aHZzLkNBRVNJQU52My1wSzA5UFhUOG8xVXJNczNXdXhVcGlvQS1iZ1ZmUXd2QWVtdU9Pa0doNEtIR2gyY3k1aWFtWmFlbEphWVRGYVNubzFhWFJvY2pRelMwaFRkMWM=