apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault
type: Opaque
data:
  token: aHZzLkNBRVNJS0UwVU16WVpFUjZfY1p5emctQkZMTEZBNEt5bmEwcDhqanBYZXRuM2ZMYkdoNEtIR2gyY3k0M1VrRnhTbU5SWkZSWU1tVnNRblJLWWxKVGRubFpibW8=