apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-external-secret
  namespace: vault
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: otus-cred
  data:
  - secretKey: username
    remoteRef:
      key: otus/cred
      property: username
  - secretKey: password
    remoteRef:
      key: otus/cred
      property: password   