apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "http://10.97.208.54:8200"
      path: "otus"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"