apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: nginx
spec:
  replicas: {{ .Values.resources.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #serviceAccountName: monitoring-service-account
      initContainers:
      - name: init-busybox
        image: busybox:latest
        command: ['sh', '-c', 'echo "Testpage ;)" > /init/index.html']
        volumeMounts:
        - mountPath: /init
          name: shared-volume
      containers:
      - name: {{ .Values.web_server.image }}
        image: {{ .Values.web_server.image }}:{{ .Values.web_server.tag }}
        volumeMounts:
        - name: shared-volume
          mountPath: /homework
        - name: new-configmap
          mountPath: /homework/conf
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
        resources:
          limits:
            cpu: {{ .Values.resources.cpu_limits }}
            memory: {{ .Values.resources.memory_limits }}
        ports:
          - containerPort: 8000
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "rm -f /homework/index.html"]
        {{- if .Values.probes.readiness }}
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - test -f /homework/index.html
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- end }}
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ .Values.storages.configmap_name1 }}
      - name: new-configmap
        configMap:
          name:  {{ .Values.storages.configmap_name2 }}
      - name: shared-volume
        persistentVolumeClaim:
          claimName: {{ .Values.storages.persistent_volume_claim }}
      nodeSelector:
        node-role: {{ .Values.nodeselector.node_role }}
        
