apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bokhanych-pvc
  namespace: homework
spec: 
  storageClassName: "bokhanych-storageclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi